import { Product } from "../../types";

export const samsungPhones: Product[] = [
  // Samsung (Phone) - 12 products
  {
    id: 'galaxy-s23-ultra',
    name: 'Samsung Galaxy S23 Ultra',
    images: ['/images/placeholder-phone.svg'],
    price: 1199,
    discountPercent: 8,
    description: 'Samsung flagship with 200MP camera and S Pen.',
    shippingInfo: 'Free shipping within 2-4 business days.',
    availability: 'in_stock',
    warranty: '1 year official warranty',
    relatedProductIds: [
      'galaxy-s23', 'galaxy-s22-ultra', 'galaxy-s22', 'galaxy-s21-ultra', 'galaxy-s21',
    ],
    detailDescription: 'The most advanced Galaxy with S Pen and 8K video.',
    details: {
      screen: {
        diagonal: '6.8 inch',
        resolution: '3088 x 1440',
        refreshRate: '120Hz',
        pixelDensity: '500 ppi',
        type: 'Dynamic AMOLED 2X',
      },
      cpu: {
        name: 'Snapdragon 8 Gen 2',
        cores: '8',
      },
      battery: {
        capacity: '5000 mAh',
      },
    },
    reviews: [
      {
        rating: 5,
        comment: 'The S Pen is super useful for notes.',
        date: '2023-02-10',
        reviewerName: 'David Black',
      },
      {
        rating: 4,
        comment: 'Camera quality is outstanding.',
        date: '2023-03-01',
        reviewerName: 'Linda White',
      },
      {
        rating: 5,
        comment: 'Battery lasts all day.',
        date: '2023-03-15',
        reviewerName: 'Tom Blue',
      },
      {
        rating: 4,
        comment: 'A bit heavy but worth it.',
        date: '2023-04-10',
        reviewerName: 'Sara Green',
      },
      {
        rating: 5,
        comment: 'Display is gorgeous and bright.',
        date: '2023-05-05',
        reviewerName: 'Alex Red',
      },
    ],
    brandId: 'samsung',
    categoryId: 'phone',
    isNewArrival: true,
    isBestseller: true,
    isFeatured: true,
  },
  {
    id: 'galaxy-s23',
    name: 'Samsung Galaxy S23',
    images: ['/images/placeholder-phone.svg'],
    price: 899,
    discountPercent: 5,
    description: 'Compact flagship with powerful performance.',
    shippingInfo: 'Free shipping within 2-4 business days.',
    availability: 'in_stock',
    warranty: '1 year official warranty',
    relatedProductIds: [
      'galaxy-s23-ultra', 'galaxy-s22-ultra', 'galaxy-s22', 'galaxy-s21-ultra', 'galaxy-s21',
    ],
    detailDescription: 'Flagship experience in a compact size.',
    details: {
      screen: {
        diagonal: '6.1 inch',
        resolution: '2340 x 1080',
        refreshRate: '120Hz',
        pixelDensity: '425 ppi',
        type: 'Dynamic AMOLED 2X',
      },
      cpu: {
        name: 'Snapdragon 8 Gen 2',
        cores: '8',
      },
      battery: {
        capacity: '3900 mAh',
      },
    },
    reviews: [
      {
        rating: 4,
        comment: 'Great size for one-handed use.',
        date: '2023-03-20',
        reviewerName: 'Megan Fox',
      },
      {
        rating: 5,
        comment: 'Performance is top tier.',
        date: '2023-04-01',
        reviewerName: 'Brian Lee',
      },
    ],
    brandId: 'samsung',
    categoryId: 'phone',
    isNewArrival: true,
  },
  {
    id: 'galaxy-s22-ultra',
    name: 'Samsung Galaxy S22 Ultra',
    images: ['/images/placeholder-phone.svg'],
    price: 1099,
    discountPercent: 10,
    description: 'S Pen built-in, 108MP camera.',
    shippingInfo: 'Free shipping within 2-4 business days.',
    availability: 'in_stock',
    warranty: '1 year official warranty',
    relatedProductIds: ['galaxy-s23-ultra', 'galaxy-s23', 'galaxy-s22', 'galaxy-s21-ultra', 'galaxy-s21'],
    detailDescription: 'S Pen built-in, 108MP camera, 5000mAh battery.',
    details: {
      screen: {
        diagonal: '6.8 inch',
        resolution: '3088 x 1440',
        refreshRate: '120Hz',
        pixelDensity: '500 ppi',
        type: 'Dynamic AMOLED 2X',
      },
      cpu: {
        name: 'Snapdragon 8 Gen 1',
        cores: '8',
      },
      battery: {
        capacity: '5000 mAh',
      },
    },
    reviews: [
      {
        rating: 5,
        comment: 'Love the S Pen.',
        date: '2023-02-15',
        reviewerName: 'Chris Blue',
      },
    ],
    brandId: 'samsung',
    categoryId: 'phone',
  },
  {
    id: 'galaxy-s22',
    name: 'Samsung Galaxy S22',
    images: ['/images/placeholder-phone.svg'],
    price: 799,
    discountPercent: 8,
    description: 'Flagship with compact design.',
    shippingInfo: 'Free shipping within 2-4 business days.',
    availability: 'in_stock',
    warranty: '1 year official warranty',
    relatedProductIds: ['galaxy-s23-ultra', 'galaxy-s23', 'galaxy-s22-ultra', 'galaxy-s21-ultra', 'galaxy-s21'],
    detailDescription: 'Compact flagship, 3700mAh battery.',
    details: {
      screen: {
        diagonal: '6.1 inch',
        resolution: '2340 x 1080',
        refreshRate: '120Hz',
        pixelDensity: '425 ppi',
        type: 'Dynamic AMOLED 2X',
      },
      cpu: {
        name: 'Snapdragon 8 Gen 1',
        cores: '8',
      },
      battery: {
        capacity: '3700 mAh',
      },
    },
    reviews: [
      {
        rating: 4,
        comment: 'Perfect size.',
        date: '2023-03-01',
        reviewerName: 'Linda Red',
      },
    ],
    brandId: 'samsung',
    categoryId: 'phone',
  },
  {
    id: 'galaxy-s21-ultra',
    name: 'Samsung Galaxy S21 Ultra',
    images: ['/images/placeholder-phone.svg'],
    price: 999,
    discountPercent: 12,
    description: 'Ultra flagship, 108MP camera.',
    shippingInfo: 'Free shipping within 2-4 business days.',
    availability: 'in_stock',
    warranty: '1 year official warranty',
    relatedProductIds: ['galaxy-s23-ultra', 'galaxy-s23', 'galaxy-s22-ultra', 'galaxy-s22', 'galaxy-s21'],
    detailDescription: '108MP camera, 5000mAh battery.',
    details: {
      screen: {
        diagonal: '6.8 inch',
        resolution: '3200 x 1440',
        refreshRate: '120Hz',
        pixelDensity: '515 ppi',
        type: 'Dynamic AMOLED 2X',
      },
      cpu: {
        name: 'Exynos 2100',
        cores: '8',
      },
      battery: {
        capacity: '5000 mAh',
      },
    },
    reviews: [
      {
        rating: 5,
        comment: 'Amazing camera.',
        date: '2023-03-10',
        reviewerName: 'Tom Black',
      },
    ],
    brandId: 'samsung',
    categoryId: 'phone',
  },
  {
    id: 'galaxy-s21',
    name: 'Samsung Galaxy S21',
    images: ['/images/placeholder-phone.svg'],
    price: 699,
    discountPercent: 10,
    description: 'Flagship with 120Hz display.',
    shippingInfo: 'Free shipping within 2-4 business days.',
    availability: 'in_stock',
    warranty: '1 year official warranty',
    relatedProductIds: ['galaxy-s23-ultra', 'galaxy-s23', 'galaxy-s22-ultra', 'galaxy-s22', 'galaxy-s21-ultra'],
    detailDescription: '120Hz display, 4000mAh battery.',
    details: {
      screen: {
        diagonal: '6.2 inch',
        resolution: '2400 x 1080',
        refreshRate: '120Hz',
        pixelDensity: '421 ppi',
        type: 'Dynamic AMOLED 2X',
      },
      cpu: {
        name: 'Exynos 2100',
        cores: '8',
      },
      battery: {
        capacity: '4000 mAh',
      },
    },
    reviews: [
      {
        rating: 4,
        comment: 'Smooth display.',
        date: '2023-03-15',
        reviewerName: 'Anna Green',
      },
    ],
    brandId: 'samsung',
    categoryId: 'phone',
  },
  {
    id: 'galaxy-s20-ultra',
    name: 'Samsung Galaxy S20 Ultra',
    images: ['/images/placeholder-phone.svg'],
    price: 899,
    discountPercent: 15,
    description: '100x Space Zoom, 5000mAh battery.',
    shippingInfo: 'Free shipping within 2-4 business days.',
    availability: 'in_stock',
    warranty: '1 year official warranty',
    relatedProductIds: ['galaxy-s23-ultra', 'galaxy-s23', 'galaxy-s22-ultra', 'galaxy-s22', 'galaxy-s21-ultra'],
    detailDescription: '100x Space Zoom, 5000mAh battery.',
    details: {
      screen: {
        diagonal: '6.9 inch',
        resolution: '3200 x 1440',
        refreshRate: '120Hz',
        pixelDensity: '511 ppi',
        type: 'Dynamic AMOLED 2X',
      },
      cpu: {
        name: 'Exynos 990',
        cores: '8',
      },
      battery: {
        capacity: '5000 mAh',
      },
    },
    reviews: [
      {
        rating: 5,
        comment: 'Space Zoom is fun.',
        date: '2023-03-20',
        reviewerName: 'Brian White',
      },
    ],
    brandId: 'samsung',
    categoryId: 'phone',
  },
  {
    id: 'galaxy-s20',
    name: 'Samsung Galaxy S20',
    images: ['/images/placeholder-phone.svg'],
    price: 599,
    discountPercent: 13,
    description: '120Hz display, 4000mAh battery.',
    shippingInfo: 'Free shipping within 2-4 business days.',
    availability: 'in_stock',
    warranty: '1 year official warranty',
    relatedProductIds: ['galaxy-s23-ultra', 'galaxy-s23', 'galaxy-s22-ultra', 'galaxy-s22', 'galaxy-s21-ultra'],
    detailDescription: '120Hz display, 4000mAh battery.',
    details: {
      screen: {
        diagonal: '6.2 inch',
        resolution: '3200 x 1440',
        refreshRate: '120Hz',
        pixelDensity: '563 ppi',
        type: 'Dynamic AMOLED 2X',
      },
      cpu: {
        name: 'Exynos 990',
        cores: '8',
      },
      battery: {
        capacity: '4000 mAh',
      },
    },
    reviews: [
      {
        rating: 4,
        comment: 'Great display.',
        date: '2023-03-25',
        reviewerName: 'Linda Blue',
      },
    ],
    brandId: 'samsung',
    categoryId: 'phone',
  },
  {
    id: 'galaxy-note20-ultra',
    name: 'Samsung Galaxy Note20 Ultra',
    images: ['/images/placeholder-phone.svg'],
    price: 999,
    discountPercent: 18,
    description: 'S Pen, 120Hz display.',
    shippingInfo: 'Free shipping within 2-4 business days.',
    availability: 'in_stock',
    warranty: '1 year official warranty',
    relatedProductIds: ['galaxy-s23-ultra', 'galaxy-s23', 'galaxy-s22-ultra', 'galaxy-s22', 'galaxy-s21-ultra'],
    detailDescription: 'S Pen, 120Hz display, 4500mAh battery.',
    details: {
      screen: {
        diagonal: '6.9 inch',
        resolution: '3088 x 1440',
        refreshRate: '120Hz',
        pixelDensity: '496 ppi',
        type: 'Dynamic AMOLED 2X',
      },
      cpu: {
        name: 'Exynos 990',
        cores: '8',
      },
      battery: {
        capacity: '4500 mAh',
      },
    },
    reviews: [
      {
        rating: 5,
        comment: 'Love the Note series.',
        date: '2023-04-01',
        reviewerName: 'Tom White',
      },
    ],
    brandId: 'samsung',
    categoryId: 'phone',
  },
  {
    id: 'galaxy-note20',
    name: 'Samsung Galaxy Note20',
    images: ['/images/placeholder-phone.svg'],
    price: 799,
    discountPercent: 16,
    description: 'S Pen, 4300mAh battery.',
    shippingInfo: 'Free shipping within 2-4 business days.',
    availability: 'in_stock',
    warranty: '1 year official warranty',
    relatedProductIds: ['galaxy-s23-ultra', 'galaxy-s23', 'galaxy-s22-ultra', 'galaxy-s22', 'galaxy-s21-ultra'],
    detailDescription: 'S Pen, 4300mAh battery.',
    details: {
      screen: {
        diagonal: '6.7 inch',
        resolution: '2400 x 1080',
        refreshRate: '60Hz',
        pixelDensity: '393 ppi',
        type: 'Super AMOLED Plus',
      },
      cpu: {
        name: 'Exynos 990',
        cores: '8',
      },
      battery: {
        capacity: '4300 mAh',
      },
    },
    reviews: [
      {
        rating: 4,
        comment: 'Great for productivity.',
        date: '2023-04-05',
        reviewerName: 'Anna Black',
      },
    ],
    brandId: 'samsung',
    categoryId: 'phone',
  },
  {
    id: 'galaxy-a54',
    name: 'Samsung Galaxy A54',
    images: ['/images/placeholder-phone.svg'],
    price: 399,
    discountPercent: 10,
    description: 'Affordable 5G phone.',
    shippingInfo: 'Free shipping within 2-4 business days.',
    availability: 'in_stock',
    warranty: '1 year official warranty',
    relatedProductIds: ['galaxy-s23-ultra', 'galaxy-s23', 'galaxy-s22-ultra', 'galaxy-s22', 'galaxy-s21-ultra'],
    detailDescription: 'Affordable 5G, 5000mAh battery.',
    details: {
      screen: {
        diagonal: '6.4 inch',
        resolution: '2340 x 1080',
        refreshRate: '120Hz',
        pixelDensity: '403 ppi',
        type: 'Super AMOLED',
      },
      cpu: {
        name: 'Exynos 1380',
        cores: '8',
      },
      battery: {
        capacity: '5000 mAh',
      },
    },
    reviews: [
      {
        rating: 4,
        comment: 'Great value.',
        date: '2023-04-10',
        reviewerName: 'Brian Green',
      },
    ],
    brandId: 'samsung',
    categoryId: 'phone',
  },
  {
    id: 'galaxy-a34',
    name: 'Samsung Galaxy A34',
    images: ['/images/placeholder-phone.svg'],
    price: 299,
    discountPercent: 12,
    description: 'Affordable 5G phone.',
    shippingInfo: 'Free shipping within 2-4 business days.',
    availability: 'in_stock',
    warranty: '1 year official warranty',
    relatedProductIds: ['galaxy-s23-ultra', 'galaxy-s23', 'galaxy-s22-ultra', 'galaxy-s22', 'galaxy-s21-ultra'],
    detailDescription: 'Affordable 5G, 5000mAh battery.',
    details: {
      screen: {
        diagonal: '6.6 inch',
        resolution: '2340 x 1080',
        refreshRate: '120Hz',
        pixelDensity: '390 ppi',
        type: 'Super AMOLED',
      },
      cpu: {
        name: 'Dimensity 1080',
        cores: '8',
      },
      battery: {
        capacity: '5000 mAh',
      },
    },
    reviews: [
      {
        rating: 4,
        comment: 'Solid midrange.',
        date: '2023-04-15',
        reviewerName: 'Linda Green',
      },
    ],
    brandId: 'samsung',
    categoryId: 'phone',
  },
  {
    id: 'galaxy-m54',
    name: 'Samsung Galaxy M54',
    images: ['/images/placeholder-phone.svg'],
    price: 349,
    discountPercent: 14,
    description: 'Big battery, affordable price.',
    shippingInfo: 'Free shipping within 2-4 business days.',
    availability: 'in_stock',
    warranty: '1 year official warranty',
    relatedProductIds: ['galaxy-s23-ultra', 'galaxy-s23', 'galaxy-s22-ultra', 'galaxy-s22', 'galaxy-s21-ultra'],
    detailDescription: '6000mAh battery, 108MP camera.',
    details: {
      screen: {
        diagonal: '6.7 inch',
        resolution: '2400 x 1080',
        refreshRate: '120Hz',
        pixelDensity: '393 ppi',
        type: 'Super AMOLED Plus',
      },
      cpu: {
        name: 'Exynos 1380',
        cores: '8',
      },
      battery: {
        capacity: '6000 mAh',
      },
    },
    reviews: [
      {
        rating: 4,
        comment: 'Battery lasts forever.',
        date: '2023-04-20',
        reviewerName: 'Tom Blue',
      },
    ],
    brandId: 'samsung',
    categoryId: 'phone',
  },
]