import { Product } from "../../types";

export const asusComputers: Product[] = [
   // Asus (Computer) - 8 products
   {
    id: 'asus-zenbook-14-oled',
    name: 'ASUS ZenBook 14 OLED',
    images: [`${process.env.API_URL}/images/placeholder-computer.svg`],
    price: 1199,
    discountPercent: 10,
    description: 'Premium ultrabook with stunning OLED display.',
    shippingInfo: 'Free shipping within 3-5 business days.',
    availability: 'in_stock',
    warranty: '1 year premium support',
    relatedProductIds: ['asus-rog-zephyrus-g14', 'asus-vivobook-15', 'asus-tuf-gaming-a15', 'asus-chromebook-flip', 'asus-expertbook-b9'],
    detailDescription: '13th Gen Intel Core i7, 16GB RAM, 512GB SSD, 14" 2.8K OLED display.',
    details: {
      processor: {
        brand: 'Intel',
        model: 'Core i7-1355U',
        cores: '10',
        threads: '12',
        baseSpeed: '1.7 GHz',
        maxSpeed: '5.0 GHz',
      },
      memory: {
        capacity: '16 GB',
        type: 'LPDDR5',
        speed: '5200 MHz',
      },
      storage: {
        capacity: '512 GB',
        type: 'PCIe NVMe SSD',
      },
      display: {
        size: '14 inch',
        resolution: '2880 x 1800',
        type: 'OLED',
        refreshRate: '90 Hz',
      },
      graphics: {
        type: 'Integrated',
        model: 'Intel Iris Xe',
      },
      battery: {
        capacity: '75 Wh',
        life: 'Up to 13 hours',
      },
    },
    reviews: [
      {
        rating: 5,
        comment: 'Beautiful OLED display and great performance!',
        date: '2023-05-01',
        reviewerName: 'Alex Chen',
      },
      {
        rating: 4,
        comment: 'Excellent build quality and design.',
        date: '2023-05-10',
        reviewerName: 'Sarah Wilson',
      },
      {
        rating: 5,
        comment: 'Perfect for creative work.',
        date: '2023-05-15',
        reviewerName: 'Michael Brown',
      },
    ],
    brandId: 'asus',
    categoryId: 'computer',
    isNewArrival: true,
    isFeatured: true,
  },
  {
    id: 'asus-rog-zephyrus-g14',
    name: 'ASUS ROG Zephyrus G14',
    images: [`${process.env.API_URL}/images/placeholder-computer.svg`],
    price: 1499,
    discountPercent: 8,
    description: 'Gaming laptop with AMD Ryzen and RTX graphics.',
    shippingInfo: 'Free shipping within 3-5 business days.',
    availability: 'in_stock',
    warranty: '1 year premium support',
    relatedProductIds: ['asus-zenbook-14-oled', 'asus-vivobook-15', 'asus-tuf-gaming-a15', 'asus-chromebook-flip', 'asus-expertbook-b9'],
    detailDescription: 'AMD Ryzen 9 7940HS, 16GB RAM, 512GB SSD, 14" QHD display, RTX 4060.',
    details: {
      processor: {
        brand: 'AMD',
        model: 'Ryzen 9 7940HS',
        cores: '8',
        threads: '16',
        baseSpeed: '4.0 GHz',
        maxSpeed: '5.2 GHz',
      },
      memory: {
        capacity: '16 GB',
        type: 'DDR5',
        speed: '5600 MHz',
      },
      storage: {
        capacity: '512 GB',
        type: 'PCIe NVMe SSD',
      },
      display: {
        size: '14 inch',
        resolution: '2560 x 1600',
        type: 'IPS',
        refreshRate: '165 Hz',
      },
      graphics: {
        type: 'Dedicated',
        model: 'NVIDIA RTX 4060',
        memory: '8 GB GDDR6',
      },
      battery: {
        capacity: '76 Wh',
        life: 'Up to 8 hours',
      },
    },
    reviews: [
      {
        rating: 5,
        comment: 'Incredible gaming performance in a compact size!',
        date: '2023-05-20',
        reviewerName: 'David Lee',
      },
      {
        rating: 4,
        comment: 'Great for both gaming and productivity.',
        date: '2023-05-25',
        reviewerName: 'Emma Davis',
      },
    ],
    brandId: 'asus',
    categoryId: 'computer',
    isBestseller: true,
  },
  {
    id: 'asus-vivobook-15',
    name: 'ASUS VivoBook 15',
    images: [`${process.env.API_URL}/images/placeholder-computer.svg`],
    price: 599,
    discountPercent: 15,
    description: 'Affordable everyday laptop with good performance.',
    shippingInfo: 'Free shipping within 3-5 business days.',
    availability: 'in_stock',
    warranty: '1 year standard support',
    relatedProductIds: ['asus-zenbook-14-oled', 'asus-rog-zephyrus-g14', 'asus-tuf-gaming-a15', 'asus-chromebook-flip', 'asus-expertbook-b9'],
    detailDescription: '13th Gen Intel Core i5, 8GB RAM, 256GB SSD, 15.6" FHD display.',
    details: {
      processor: {
        brand: 'Intel',
        model: 'Core i5-1335U',
        cores: '10',
        threads: '12',
        baseSpeed: '1.8 GHz',
        maxSpeed: '4.6 GHz',
      },
      memory: {
        capacity: '8 GB',
        type: 'DDR4',
        speed: '3200 MHz',
      },
      storage: {
        capacity: '256 GB',
        type: 'PCIe NVMe SSD',
      },
      display: {
        size: '15.6 inch',
        resolution: '1920 x 1080',
        type: 'IPS',
        refreshRate: '60 Hz',
      },
      graphics: {
        type: 'Integrated',
        model: 'Intel Iris Xe',
      },
      battery: {
        capacity: '50 Wh',
        life: 'Up to 8 hours',
      },
    },
    reviews: [
      {
        rating: 4,
        comment: 'Good value for money.',
        date: '2023-06-01',
        reviewerName: 'Lisa Anderson',
      },
    ],
    brandId: 'asus',
    categoryId: 'computer',
    isDiscount: true,
  },
  {
    id: 'asus-tuf-gaming-a15',
    name: 'ASUS TUF Gaming A15',
    images: [`${process.env.API_URL}/images/placeholder-computer.svg`],
    price: 899,
    discountPercent: 12,
    description: 'Durable gaming laptop with military-grade construction.',
    shippingInfo: 'Free shipping within 3-5 business days.',
    availability: 'in_stock',
    warranty: '1 year standard support',
    relatedProductIds: ['asus-zenbook-14-oled', 'asus-rog-zephyrus-g14', 'asus-vivobook-15', 'asus-chromebook-flip', 'asus-expertbook-b9'],
    detailDescription: 'AMD Ryzen 7 7735HS, 16GB RAM, 512GB SSD, 15.6" FHD display, RTX 4050.',
    details: {
      processor: {
        brand: 'AMD',
        model: 'Ryzen 7 7735HS',
        cores: '8',
        threads: '16',
        baseSpeed: '3.2 GHz',
        maxSpeed: '4.7 GHz',
      },
      memory: {
        capacity: '16 GB',
        type: 'DDR5',
        speed: '4800 MHz',
      },
      storage: {
        capacity: '512 GB',
        type: 'PCIe NVMe SSD',
      },
      display: {
        size: '15.6 inch',
        resolution: '1920 x 1080',
        type: 'IPS',
        refreshRate: '144 Hz',
      },
      graphics: {
        type: 'Dedicated',
        model: 'NVIDIA RTX 4050',
        memory: '6 GB GDDR6',
      },
      battery: {
        capacity: '90 Wh',
        life: 'Up to 7 hours',
      },
    },
    reviews: [
      {
        rating: 4,
        comment: 'Great gaming performance and durability.',
        date: '2023-06-05',
        reviewerName: 'Tom Wilson',
      },
    ],
    brandId: 'asus',
    categoryId: 'computer',
    isFeatured: true,
  },
  {
    id: 'asus-chromebook-flip',
    name: 'ASUS Chromebook Flip C434',
    images: [`${process.env.API_URL}/images/placeholder-computer.svg`],
    price: 449,
    discountPercent: 20,
    description: 'Premium 2-in-1 Chromebook with aluminum design.',
    shippingInfo: 'Free shipping within 3-5 business days.',
    availability: 'in_stock',
    warranty: '1 year standard support',
    relatedProductIds: ['asus-zenbook-14-oled', 'asus-rog-zephyrus-g14', 'asus-vivobook-15', 'asus-tuf-gaming-a15', 'asus-expertbook-b9'],
    detailDescription: 'Intel Core m3-8100Y, 8GB RAM, 64GB eMMC, 14" FHD touch display.',
    details: {
      processor: {
        brand: 'Intel',
        model: 'Core m3-8100Y',
        cores: '2',
        threads: '4',
        baseSpeed: '1.1 GHz',
        maxSpeed: '3.4 GHz',
      },
      memory: {
        capacity: '8 GB',
        type: 'LPDDR3',
        speed: '1866 MHz',
      },
      storage: {
        capacity: '64 GB',
        type: 'eMMC',
      },
      display: {
        size: '14 inch',
        resolution: '1920 x 1080',
        type: 'IPS Touch',
        refreshRate: '60 Hz',
      },
      graphics: {
        type: 'Integrated',
        model: 'Intel UHD Graphics 615',
      },
      battery: {
        capacity: '48 Wh',
        life: 'Up to 10 hours',
      },
    },
    reviews: [
      {
        rating: 4,
        comment: 'Great Chromebook for productivity.',
        date: '2023-06-10',
        reviewerName: 'Maria Garcia',
      },
    ],
    brandId: 'asus',
    categoryId: 'computer',
    isDiscount: true,
  },
  {
    id: 'asus-expertbook-b9',
    name: 'ASUS ExpertBook B9',
    images: [`${process.env.API_URL}/images/placeholder-computer.svg`],
    price: 1699,
    discountPercent: 5,
    description: 'Ultra-lightweight business laptop with premium features.',
    shippingInfo: 'Free shipping within 3-5 business days.',
    availability: 'in_stock',
    warranty: '3 year premium support',
    relatedProductIds: ['asus-zenbook-14-oled', 'asus-rog-zephyrus-g14', 'asus-vivobook-15', 'asus-tuf-gaming-a15', 'asus-chromebook-flip'],
    detailDescription: '13th Gen Intel Core i7, 16GB RAM, 512GB SSD, 14" FHD display.',
    details: {
      processor: {
        brand: 'Intel',
        model: 'Core i7-1355U',
        cores: '10',
        threads: '12',
        baseSpeed: '1.7 GHz',
        maxSpeed: '5.0 GHz',
      },
      memory: {
        capacity: '16 GB',
        type: 'LPDDR5',
        speed: '5200 MHz',
      },
      storage: {
        capacity: '512 GB',
        type: 'PCIe NVMe SSD',
      },
      display: {
        size: '14 inch',
        resolution: '1920 x 1080',
        type: 'IPS',
        refreshRate: '60 Hz',
      },
      graphics: {
        type: 'Integrated',
        model: 'Intel Iris Xe',
      },
      battery: {
        capacity: '66 Wh',
        life: 'Up to 12 hours',
      },
    },
    reviews: [
      {
        rating: 5,
        comment: 'Incredibly light and powerful.',
        date: '2023-06-15',
        reviewerName: 'Robert Smith',
      },
    ],
    brandId: 'asus',
    categoryId: 'computer',
    isNewArrival: true,
  },
  {
    id: 'asus-zenbook-duo-14',
    name: 'ASUS ZenBook Duo 14',
    images: [`${process.env.API_URL}/images/placeholder-computer.svg`],
    price: 1399,
    discountPercent: 10,
    description: 'Dual-screen laptop for enhanced productivity.',
    shippingInfo: 'Free shipping within 3-5 business days.',
    availability: 'in_stock',
    warranty: '1 year premium support',
    relatedProductIds: ['asus-zenbook-14-oled', 'asus-rog-zephyrus-g14', 'asus-vivobook-15', 'asus-tuf-gaming-a15', 'asus-chromebook-flip'],
    detailDescription: '12th Gen Intel Core i7, 16GB RAM, 512GB SSD, 14" FHD + 12.6" ScreenPad Plus.',
    details: {
      processor: {
        brand: 'Intel',
        model: 'Core i7-12700H',
        cores: '14',
        threads: '20',
        baseSpeed: '2.3 GHz',
        maxSpeed: '4.7 GHz',
      },
      memory: {
        capacity: '16 GB',
        type: 'DDR5',
        speed: '4800 MHz',
      },
      storage: {
        capacity: '512 GB',
        type: 'PCIe NVMe SSD',
      },
      display: {
        size: '14 inch + 12.6 inch',
        resolution: '1920 x 1080 + 1920 x 515',
        type: 'IPS + IPS',
        refreshRate: '60 Hz',
      },
      graphics: {
        type: 'Integrated',
        model: 'Intel Iris Xe',
      },
      battery: {
        capacity: '70 Wh',
        life: 'Up to 10 hours',
      },
    },
    reviews: [
      {
        rating: 4,
        comment: 'Innovative dual-screen design.',
        date: '2023-06-20',
        reviewerName: 'Chris Rodriguez',
      },
    ],
    brandId: 'asus',
    categoryId: 'computer',
    isFeatured: true,
  },
  {
    id: 'asus-rog-strix-g15',
    name: 'ASUS ROG Strix G15',
    images: [`${process.env.API_URL}/images/placeholder-computer.svg`],
    price: 1299,
    discountPercent: 8,
    description: 'Gaming laptop with aggressive design and RGB lighting.',
    shippingInfo: 'Free shipping within 3-5 business days.',
    availability: 'in_stock',
    warranty: '1 year standard support',
    relatedProductIds: ['asus-zenbook-14-oled', 'asus-rog-zephyrus-g14', 'asus-vivobook-15', 'asus-tuf-gaming-a15', 'asus-chromebook-flip'],
    detailDescription: 'AMD Ryzen 7 7735HS, 16GB RAM, 512GB SSD, 15.6" QHD display, RTX 4060.',
    details: {
      processor: {
        brand: 'AMD',
        model: 'Ryzen 7 7735HS',
        cores: '8',
        threads: '16',
        baseSpeed: '3.2 GHz',
        maxSpeed: '4.7 GHz',
      },
      memory: {
        capacity: '16 GB',
        type: 'DDR5',
        speed: '4800 MHz',
      },
      storage: {
        capacity: '512 GB',
        type: 'PCIe NVMe SSD',
      },
      display: {
        size: '15.6 inch',
        resolution: '2560 x 1440',
        type: 'IPS',
        refreshRate: '165 Hz',
      },
      graphics: {
        type: 'Dedicated',
        model: 'NVIDIA RTX 4060',
        memory: '8 GB GDDR6',
      },
      battery: {
        capacity: '90 Wh',
        life: 'Up to 6 hours',
      },
    },
    reviews: [
      {
        rating: 5,
        comment: 'Amazing gaming performance with great cooling!',
        date: '2023-06-25',
        reviewerName: 'Kevin Martinez',
      },
    ],
    brandId: 'asus',
    categoryId: 'computer',
    isBestseller: true,
  }, 
]