import { Product } from "../../types";

export const lenovoComputers: Product[] = [
   // Lenovo (Computer) - 10 products
   {
    id: 'lenovo-thinkpad-x1-carbon',
    name: 'Lenovo ThinkPad X1 Carbon',
    images: ['/images/placeholder-computer.svg'],
    price: 1499,
    discountPercent: 8,
    description: 'Premium business ultrabook with legendary durability.',
    shippingInfo: 'Free shipping within 3-5 business days.',
    availability: 'in_stock',
    warranty: '3 year premium support',
    relatedProductIds: ['lenovo-yoga-9i', 'lenovo-ideapad-pro', 'lenovo-legion-5', 'lenovo-thinkbook-14', 'lenovo-chromebook-flex'],
    detailDescription: '13th Gen Intel Core i7, 16GB RAM, 512GB SSD, 14" 2.8K OLED display.',
    details: {
      processor: {
        brand: 'Intel',
        model: 'Core i7-1355U',
        cores: '10',
        threads: '12',
        baseSpeed: '1.7 GHz',
        maxSpeed: '5.0 GHz',
      },
      memory: {
        capacity: '16 GB',
        type: 'LPDDR5',
        speed: '5200 MHz',
      },
      storage: {
        capacity: '512 GB',
        type: 'PCIe NVMe SSD',
      },
      display: {
        size: '14 inch',
        resolution: '2880 x 1800',
        type: 'OLED',
        refreshRate: '60 Hz',
      },
      graphics: {
        type: 'Integrated',
        model: 'Intel Iris Xe',
      },
      battery: {
        capacity: '57 Wh',
        life: 'Up to 15 hours',
      },
    },
    reviews: [
      {
        rating: 5,
        comment: 'Best business laptop I\'ve ever used!',
        date: '2023-05-01',
        reviewerName: 'Michael Chen',
      },
      {
        rating: 4,
        comment: 'Excellent build quality and keyboard.',
        date: '2023-05-10',
        reviewerName: 'Sarah Johnson',
      },
      {
        rating: 5,
        comment: 'Perfect for business travel.',
        date: '2023-05-15',
        reviewerName: 'David Wilson',
      },
    ],
    brandId: 'lenovo',
    categoryId: 'computer',
    isNewArrival: true,
    isFeatured: true,
  },
  {
    id: 'lenovo-yoga-9i',
    name: 'Lenovo Yoga 9i',
    images: ['/images/placeholder-computer.svg'],
    price: 1299,
    discountPercent: 10,
    description: 'Premium 2-in-1 convertible with rotating soundbar.',
    shippingInfo: 'Free shipping within 3-5 business days.',
    availability: 'in_stock',
    warranty: '1 year premium support',
    relatedProductIds: ['lenovo-thinkpad-x1-carbon', 'lenovo-ideapad-pro', 'lenovo-legion-5', 'lenovo-thinkbook-14', 'lenovo-chromebook-flex'],
    detailDescription: '13th Gen Intel Core i7, 16GB RAM, 512GB SSD, 14" 2.8K OLED display.',
    details: {
      processor: {
        brand: 'Intel',
        model: 'Core i7-1355U',
        cores: '10',
        threads: '12',
        baseSpeed: '1.7 GHz',
        maxSpeed: '5.0 GHz',
      },
      memory: {
        capacity: '16 GB',
        type: 'LPDDR5',
        speed: '5200 MHz',
      },
      storage: {
        capacity: '512 GB',
        type: 'PCIe NVMe SSD',
      },
      display: {
        size: '14 inch',
        resolution: '2880 x 1800',
        type: 'OLED',
        refreshRate: '60 Hz',
      },
      graphics: {
        type: 'Integrated',
        model: 'Intel Iris Xe',
      },
      battery: {
        capacity: '75 Wh',
        life: 'Up to 13 hours',
      },
    },
    reviews: [
      {
        rating: 4,
        comment: 'Beautiful design and great 2-in-1 functionality.',
        date: '2023-05-20',
        reviewerName: 'Emma Davis',
      },
      {
        rating: 5,
        comment: 'Amazing sound quality with the rotating soundbar.',
        date: '2023-05-25',
        reviewerName: 'James Brown',
      },
    ],
    brandId: 'lenovo',
    categoryId: 'computer',
    isBestseller: true,
  },
  {
    id: 'lenovo-ideapad-pro',
    name: 'Lenovo IdeaPad Pro',
    images: ['/images/placeholder-computer.svg'],
    price: 899,
    discountPercent: 12,
    description: 'Creative laptop with RTX graphics.',
    shippingInfo: 'Free shipping within 3-5 business days.',
    availability: 'in_stock',
    warranty: '1 year standard support',
    relatedProductIds: ['lenovo-thinkpad-x1-carbon', 'lenovo-yoga-9i', 'lenovo-legion-5', 'lenovo-thinkbook-14', 'lenovo-chromebook-flex'],
    detailDescription: '13th Gen Intel Core i5, 16GB RAM, 512GB SSD, 16" 2.5K display, RTX 4050.',
    details: {
      processor: {
        brand: 'Intel',
        model: 'Core i5-13500H',
        cores: '14',
        threads: '20',
        baseSpeed: '2.6 GHz',
        maxSpeed: '4.7 GHz',
      },
      memory: {
        capacity: '16 GB',
        type: 'DDR5',
        speed: '5200 MHz',
      },
      storage: {
        capacity: '512 GB',
        type: 'PCIe NVMe SSD',
      },
      display: {
        size: '16 inch',
        resolution: '2560 x 1600',
        type: 'IPS',
        refreshRate: '120 Hz',
      },
      graphics: {
        type: 'Dedicated',
        model: 'NVIDIA RTX 4050',
        memory: '6 GB GDDR6',
      },
      battery: {
        capacity: '75 Wh',
        life: 'Up to 8 hours',
      },
    },
    reviews: [
      {
        rating: 4,
        comment: 'Great for creative work and light gaming.',
        date: '2023-06-01',
        reviewerName: 'Lisa Anderson',
      },
    ],
    brandId: 'lenovo',
    categoryId: 'computer',
    isDiscount: true,
  },
  {
    id: 'lenovo-legion-5',
    name: 'Lenovo Legion 5',
    images: ['/images/placeholder-computer.svg'],
    price: 999,
    discountPercent: 15,
    description: 'Gaming laptop with excellent performance.',
    shippingInfo: 'Free shipping within 3-5 business days.',
    availability: 'in_stock',
    warranty: '1 year standard support',
    relatedProductIds: ['lenovo-thinkpad-x1-carbon', 'lenovo-yoga-9i', 'lenovo-ideapad-pro', 'lenovo-thinkbook-14', 'lenovo-chromebook-flex'],
    detailDescription: '12th Gen Intel Core i7, 16GB RAM, 512GB SSD, 15.6" FHD display, RTX 4060.',
    details: {
      processor: {
        brand: 'Intel',
        model: 'Core i7-12700H',
        cores: '14',
        threads: '20',
        baseSpeed: '2.3 GHz',
        maxSpeed: '4.7 GHz',
      },
      memory: {
        capacity: '16 GB',
        type: 'DDR5',
        speed: '4800 MHz',
      },
      storage: {
        capacity: '512 GB',
        type: 'PCIe NVMe SSD',
      },
      display: {
        size: '15.6 inch',
        resolution: '1920 x 1080',
        type: 'IPS',
        refreshRate: '165 Hz',
      },
      graphics: {
        type: 'Dedicated',
        model: 'NVIDIA RTX 4060',
        memory: '8 GB GDDR6',
      },
      battery: {
        capacity: '80 Wh',
        life: 'Up to 6 hours',
      },
    },
    reviews: [
      {
        rating: 5,
        comment: 'Excellent gaming performance!',
        date: '2023-06-05',
        reviewerName: 'Tom Wilson',
      },
    ],
    brandId: 'lenovo',
    categoryId: 'computer',
    isFeatured: true,
  },
  {
    id: 'lenovo-thinkbook-14',
    name: 'Lenovo ThinkBook 14',
    images: ['/images/placeholder-computer.svg'],
    price: 699,
    discountPercent: 10,
    description: 'Business laptop with modern design.',
    shippingInfo: 'Free shipping within 3-5 business days.',
    availability: 'in_stock',
    warranty: '1 year standard support',
    relatedProductIds: ['lenovo-thinkpad-x1-carbon', 'lenovo-yoga-9i', 'lenovo-ideapad-pro', 'lenovo-legion-5', 'lenovo-chromebook-flex'],
    detailDescription: '13th Gen Intel Core i5, 8GB RAM, 256GB SSD, 14" FHD display.',
    details: {
      processor: {
        brand: 'Intel',
        model: 'Core i5-1335U',
        cores: '10',
        threads: '12',
        baseSpeed: '1.8 GHz',
        maxSpeed: '4.6 GHz',
      },
      memory: {
        capacity: '8 GB',
        type: 'DDR4',
        speed: '3200 MHz',
      },
      storage: {
        capacity: '256 GB',
        type: 'PCIe NVMe SSD',
      },
      display: {
        size: '14 inch',
        resolution: '1920 x 1080',
        type: 'IPS',
        refreshRate: '60 Hz',
      },
      graphics: {
        type: 'Integrated',
        model: 'Intel Iris Xe',
      },
      battery: {
        capacity: '60 Wh',
        life: 'Up to 10 hours',
      },
    },
    reviews: [
      {
        rating: 4,
        comment: 'Good value for business use.',
        date: '2023-06-10',
        reviewerName: 'Robert Smith',
      },
    ],
    brandId: 'lenovo',
    categoryId: 'computer',
    isBestseller: true,
  },
  {
    id: 'lenovo-chromebook-flex',
    name: 'Lenovo Chromebook Flex 5',
    images: ['/images/placeholder-computer.svg'],
    price: 399,
    discountPercent: 20,
    description: 'Affordable 2-in-1 Chromebook.',
    shippingInfo: 'Free shipping within 3-5 business days.',
    availability: 'in_stock',
    warranty: '1 year standard support',
    relatedProductIds: ['lenovo-thinkpad-x1-carbon', 'lenovo-yoga-9i', 'lenovo-ideapad-pro', 'lenovo-legion-5', 'lenovo-thinkbook-14'],
    detailDescription: 'Intel Core i3-1115G4, 8GB RAM, 128GB SSD, 13.3" FHD touch display.',
    details: {
      processor: {
        brand: 'Intel',
        model: 'Core i3-1115G4',
        cores: '2',
        threads: '4',
        baseSpeed: '3.0 GHz',
        maxSpeed: '4.1 GHz',
      },
      memory: {
        capacity: '8 GB',
        type: 'DDR4',
        speed: '3200 MHz',
      },
      storage: {
        capacity: '128 GB',
        type: 'PCIe NVMe SSD',
      },
      display: {
        size: '13.3 inch',
        resolution: '1920 x 1080',
        type: 'IPS Touch',
        refreshRate: '60 Hz',
      },
      graphics: {
        type: 'Integrated',
        model: 'Intel UHD Graphics',
      },
      battery: {
        capacity: '51 Wh',
        life: 'Up to 10 hours',
      },
    },
    reviews: [
      {
        rating: 4,
        comment: 'Great for students and basic tasks.',
        date: '2023-06-15',
        reviewerName: 'Maria Garcia',
      },
    ],
    brandId: 'lenovo',
    categoryId: 'computer',
    isDiscount: true,
  },
  {
    id: 'lenovo-legion-7',
    name: 'Lenovo Legion 7',
    images: ['/images/placeholder-computer.svg'],
    price: 1799,
    discountPercent: 8,
    description: 'Premium gaming laptop with advanced features.',
    shippingInfo: 'Free shipping within 3-5 business days.',
    availability: 'in_stock',
    warranty: '1 year premium support',
    relatedProductIds: ['lenovo-thinkpad-x1-carbon', 'lenovo-yoga-9i', 'lenovo-ideapad-pro', 'lenovo-legion-5', 'lenovo-thinkbook-14'],
    detailDescription: '13th Gen Intel Core i7, 32GB RAM, 1TB SSD, 16" QHD display, RTX 4070.',
    details: {
      processor: {
        brand: 'Intel',
        model: 'Core i7-13700H',
        cores: '14',
        threads: '20',
        baseSpeed: '2.4 GHz',
        maxSpeed: '5.0 GHz',
      },
      memory: {
        capacity: '32 GB',
        type: 'DDR5',
        speed: '5200 MHz',
      },
      storage: {
        capacity: '1 TB',
        type: 'PCIe NVMe SSD',
      },
      display: {
        size: '16 inch',
        resolution: '2560 x 1600',
        type: 'IPS',
        refreshRate: '240 Hz',
      },
      graphics: {
        type: 'Dedicated',
        model: 'NVIDIA RTX 4070',
        memory: '8 GB GDDR6',
      },
      battery: {
        capacity: '99.9 Wh',
        life: 'Up to 7 hours',
      },
    },
    reviews: [
      {
        rating: 5,
        comment: 'Incredible gaming performance!',
        date: '2023-06-20',
        reviewerName: 'Chris Rodriguez',
      },
    ],
    brandId: 'lenovo',
    categoryId: 'computer',
    isNewArrival: true,
  },
  {
    id: 'lenovo-yoga-slim-7',
    name: 'Lenovo Yoga Slim 7',
    images: ['/images/placeholder-computer.svg'],
    price: 799,
    discountPercent: 12,
    description: 'Slim and lightweight ultrabook.',
    shippingInfo: 'Free shipping within 3-5 business days.',
    availability: 'in_stock',
    warranty: '1 year standard support',
    relatedProductIds: ['lenovo-thinkpad-x1-carbon', 'lenovo-yoga-9i', 'lenovo-ideapad-pro', 'lenovo-legion-5', 'lenovo-thinkbook-14'],
    detailDescription: 'AMD Ryzen 7 7735U, 16GB RAM, 512GB SSD, 14" 2.8K display.',
    details: {
      processor: {
        brand: 'AMD',
        model: 'Ryzen 7 7735U',
        cores: '8',
        threads: '16',
        baseSpeed: '2.7 GHz',
        maxSpeed: '4.7 GHz',
      },
      memory: {
        capacity: '16 GB',
        type: 'LPDDR5',
        speed: '6400 MHz',
      },
      storage: {
        capacity: '512 GB',
        type: 'PCIe NVMe SSD',
      },
      display: {
        size: '14 inch',
        resolution: '2880 x 1800',
        type: 'OLED',
        refreshRate: '90 Hz',
      },
      graphics: {
        type: 'Integrated',
        model: 'AMD Radeon 680M',
      },
      battery: {
        capacity: '70 Wh',
        life: 'Up to 12 hours',
      },
    },
    reviews: [
      {
        rating: 4,
        comment: 'Great performance and battery life.',
        date: '2023-06-25',
        reviewerName: 'Anna Lee',
      },
    ],
    brandId: 'lenovo',
    categoryId: 'computer',
  },
  {
    id: 'lenovo-ideapad-3',
    name: 'Lenovo IdeaPad 3',
    images: ['/images/placeholder-computer.svg'],
    price: 449,
    discountPercent: 15,
    description: 'Affordable everyday laptop.',
    shippingInfo: 'Free shipping within 3-5 business days.',
    availability: 'in_stock',
    warranty: '1 year standard support',
    relatedProductIds: ['lenovo-thinkpad-x1-carbon', 'lenovo-yoga-9i', 'lenovo-ideapad-pro', 'lenovo-legion-5', 'lenovo-thinkbook-14'],
    detailDescription: 'AMD Ryzen 5 7520U, 8GB RAM, 256GB SSD, 15.6" FHD display.',
    details: {
      processor: {
        brand: 'AMD',
        model: 'Ryzen 5 7520U',
        cores: '4',
        threads: '8',
        baseSpeed: '2.8 GHz',
        maxSpeed: '4.3 GHz',
      },
      memory: {
        capacity: '8 GB',
        type: 'DDR4',
        speed: '3200 MHz',
      },
      storage: {
        capacity: '256 GB',
        type: 'PCIe NVMe SSD',
      },
      display: {
        size: '15.6 inch',
        resolution: '1920 x 1080',
        type: 'TN',
        refreshRate: '60 Hz',
      },
      graphics: {
        type: 'Integrated',
        model: 'AMD Radeon Graphics',
      },
      battery: {
        capacity: '45 Wh',
        life: 'Up to 8 hours',
      },
    },
    reviews: [
      {
        rating: 3,
        comment: 'Basic but functional for daily tasks.',
        date: '2023-07-01',
        reviewerName: 'John Smith',
      },
    ],
    brandId: 'lenovo',
    categoryId: 'computer',
    isDiscount: true,
  },
  {
    id: 'lenovo-thinkpad-e14',
    name: 'Lenovo ThinkPad E14',
    images: ['/images/placeholder-computer.svg'],
    price: 599,
    discountPercent: 10,
    description: 'Entry-level ThinkPad for business.',
    shippingInfo: 'Free shipping within 3-5 business days.',
    availability: 'in_stock',
    warranty: '1 year standard support',
    relatedProductIds: ['lenovo-thinkpad-x1-carbon', 'lenovo-yoga-9i', 'lenovo-ideapad-pro', 'lenovo-legion-5', 'lenovo-thinkbook-14'],
    detailDescription: '12th Gen Intel Core i5, 8GB RAM, 256GB SSD, 14" FHD display.',
    details: {
      processor: {
        brand: 'Intel',
        model: 'Core i5-1235U',
        cores: '10',
        threads: '12',
        baseSpeed: '1.3 GHz',
        maxSpeed: '4.4 GHz',
      },
      memory: {
        capacity: '8 GB',
        type: 'DDR4',
        speed: '3200 MHz',
      },
      storage: {
        capacity: '256 GB',
        type: 'PCIe NVMe SSD',
      },
      display: {
        size: '14 inch',
        resolution: '1920 x 1080',
        type: 'IPS',
        refreshRate: '60 Hz',
      },
      graphics: {
        type: 'Integrated',
        model: 'Intel Iris Xe',
      },
      battery: {
        capacity: '45 Wh',
        life: 'Up to 9 hours',
      },
    },
    reviews: [
      {
        rating: 4,
        comment: 'Good entry-level ThinkPad.',
        date: '2023-07-05',
        reviewerName: 'Mark Johnson',
      },
    ],
    brandId: 'lenovo',
    categoryId: 'computer',
  }, 
]