import { Product } from '../../types';

export const microsoftComputers: Product[] = [
  // Microsoft (Computer) - 4 products
  {
    id: 'surface-laptop-studio-2',
    name: 'Surface Laptop Studio 2',
    images: [`${process.env.API_URL}/images/placeholder-computer.svg`],
    price: 1999,
    discountPercent: 5,
    description: 'Versatile 2-in-1 laptop with Intel Core i7 and RTX 4060.',
    shippingInfo: 'Free shipping within 3-5 business days.',
    availability: 'in_stock',
    warranty: '1 year Microsoft warranty',
    relatedProductIds: ['surface-laptop-5', 'surface-pro-9', 'surface-laptop-go-3'],
    detailDescription: 'Intel Core i7-13700H, 16GB RAM, 512GB SSD, 14.4" PixelSense Flow display, RTX 4060.',
    details: {
      processor: {
        brand: 'Intel',
        model: 'Core i7-13700H',
        cores: '14',
        threads: '20',
        baseSpeed: '2.4 GHz',
        maxSpeed: '5.0 GHz',
      },
      memory: {
        capacity: '16 GB',
        type: 'LPDDR5',
        speed: '5200 MHz',
      },
      storage: {
        capacity: '512 GB',
        type: 'PCIe NVMe SSD',
      },
      display: {
        size: '14.4 inch',
        resolution: '2400 x 1600',
        type: 'PixelSense Flow',
        refreshRate: '120 Hz',
      },
      graphics: {
        type: 'Dedicated',
        model: 'NVIDIA RTX 4060',
        memory: '8 GB GDDR6',
      },
      battery: {
        capacity: '58 Wh',
        life: 'Up to 18 hours',
      },
    },
    reviews: [
      {
        rating: 5,
        comment: 'Incredible versatility and performance!',
        date: '2023-11-01',
        reviewerName: 'Alex Johnson',
      },
      {
        rating: 4,
        comment: 'Perfect for creative work and gaming.',
        date: '2023-11-05',
        reviewerName: 'Sarah Williams',
      },
    ],
    brandId: 'microsoft',
    categoryId: 'computer',
    isNewArrival: true,
    isFeatured: true,
  },
  {
    id: 'surface-laptop-5',
    name: 'Surface Laptop 5',
    images: [`${process.env.API_URL}/images/placeholder-computer.svg`],
    price: 999,
    discountPercent: 10,
    description: 'Premium laptop with Intel Core i5 and beautiful design.',
    shippingInfo: 'Free shipping within 3-5 business days.',
    availability: 'in_stock',
    warranty: '1 year Microsoft warranty',
    relatedProductIds: ['surface-laptop-studio-2', 'surface-pro-9', 'surface-laptop-go-3'],
    detailDescription: 'Intel Core i5-1235U, 8GB RAM, 256GB SSD, 13.5" PixelSense display.',
    details: {
      processor: {
        brand: 'Intel',
        model: 'Core i5-1235U',
        cores: '10',
        threads: '12',
        baseSpeed: '1.3 GHz',
        maxSpeed: '4.4 GHz',
      },
      memory: {
        capacity: '8 GB',
        type: 'LPDDR5',
        speed: '5200 MHz',
      },
      storage: {
        capacity: '256 GB',
        type: 'PCIe NVMe SSD',
      },
      display: {
        size: '13.5 inch',
        resolution: '2256 x 1504',
        type: 'PixelSense',
        refreshRate: '60 Hz',
      },
      graphics: {
        type: 'Integrated',
        model: 'Intel Iris Xe',
      },
      battery: {
        capacity: '47.4 Wh',
        life: 'Up to 18 hours',
      },
    },
    reviews: [
      {
        rating: 4,
        comment: 'Beautiful design and great performance.',
        date: '2023-11-10',
        reviewerName: 'Emily Davis',
      },
    ],
    brandId: 'microsoft',
    categoryId: 'computer',
    isBestseller: true,
  },
  {
    id: 'surface-pro-9',
    name: 'Surface Pro 9',
    images: [`${process.env.API_URL}/images/placeholder-computer.svg`],
    price: 1099,
    discountPercent: 8,
    description: 'Versatile tablet-laptop hybrid with Intel Core i5.',
    shippingInfo: 'Free shipping within 3-5 business days.',
    availability: 'in_stock',
    warranty: '1 year Microsoft warranty',
    relatedProductIds: ['surface-laptop-studio-2', 'surface-laptop-5', 'surface-laptop-go-3'],
    detailDescription: 'Intel Core i5-1235U, 8GB RAM, 256GB SSD, 13" PixelSense display.',
    details: {
      processor: {
        brand: 'Intel',
        model: 'Core i5-1235U',
        cores: '10',
        threads: '12',
        baseSpeed: '1.3 GHz',
        maxSpeed: '4.4 GHz',
      },
      memory: {
        capacity: '8 GB',
        type: 'LPDDR5',
        speed: '5200 MHz',
      },
      storage: {
        capacity: '256 GB',
        type: 'PCIe NVMe SSD',
      },
      display: {
        size: '13 inch',
        resolution: '2880 x 1920',
        type: 'PixelSense',
        refreshRate: '120 Hz',
      },
      graphics: {
        type: 'Integrated',
        model: 'Intel Iris Xe',
      },
      battery: {
        capacity: '47.7 Wh',
        life: 'Up to 15.5 hours',
      },
    },
    reviews: [
      {
        rating: 5,
        comment: 'Perfect for productivity and creativity.',
        date: '2023-11-15',
        reviewerName: 'David Wilson',
      },
      {
        rating: 4,
        comment: 'Great tablet and laptop in one.',
        date: '2023-11-20',
        reviewerName: 'Chris Rodriguez',
      },
    ],
    brandId: 'microsoft',
    categoryId: 'computer',
    isFeatured: true,
  },
  {
    id: 'surface-laptop-go-3',
    name: 'Surface Laptop Go 3',
    images: [`${process.env.API_URL}/images/placeholder-computer.svg`],
    price: 599,
    discountPercent: 15,
    description: 'Affordable Surface laptop with Intel Core i5.',
    shippingInfo: 'Free shipping within 3-5 business days.',
    availability: 'in_stock',
    warranty: '1 year Microsoft warranty',
    relatedProductIds: ['surface-laptop-studio-2', 'surface-laptop-5', 'surface-pro-9'],
    detailDescription: 'Intel Core i5-1235U, 8GB RAM, 128GB SSD, 12.4" PixelSense display.',
    details: {
      processor: {
        brand: 'Intel',
        model: 'Core i5-1235U',
        cores: '10',
        threads: '12',
        baseSpeed: '1.3 GHz',
        maxSpeed: '4.4 GHz',
      },
      memory: {
        capacity: '8 GB',
        type: 'LPDDR5',
        speed: '5200 MHz',
      },
      storage: {
        capacity: '128 GB',
        type: 'PCIe NVMe SSD',
      },
      display: {
        size: '12.4 inch',
        resolution: '1536 x 1024',
        type: 'PixelSense',
        refreshRate: '60 Hz',
      },
      graphics: {
        type: 'Integrated',
        model: 'Intel Iris Xe',
      },
      battery: {
        capacity: '41 Wh',
        life: 'Up to 15 hours',
      },
    },
    reviews: [
      {
        rating: 4,
        comment: 'Great value for a Surface device.',
        date: '2023-11-25',
        reviewerName: 'Lisa Thompson',
      },
    ],
    brandId: 'microsoft',
    categoryId: 'computer',
    isDiscount: true,
  },
]; 